### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by c0d3z3r0** [pts/pts-dropbear#5]
Hi,

When do you plan to send the patches to upstream?

**Comment by pts** [comment]
I already did: http://lists.ucc.gu.uwa.edu.au/pipermail/dropbear/2017q4/002036.html

Also I created the branch https://github.com/pts/dropbear-ptscrypto/tree/ptscrypto on 2017-10-05 according to the instructions, so that my changes are easy to merge. Now it's up to the Dropbear developers to merge my changes.
